### ISSUE TITLE
Is libSQL a library or a RDBMS?

### ISSUE THREAD

**Issue by zeritonius** [libsql/libsql#31]
SQLite is a RDBMS.

To me, the name libSQL suggests a lib (library). Is libSQL a library or a RDBMS?

IMHO, I think this should be mentioned in the msin description or in a FAQ.

To me, a name create certain expectations. SQLite suggests something lite. If you saw the name libSQL for the first time, what would think of? 

Thank you.

**Comment by tjyang** [comment]
I had same question why picking a library name until I see https://github.com/libsql/libsql/issues/25.

**Comment by psarna** [comment]
libSQL is a fork for of SQLite, and their main page (https://sqlite.org) starts with `SQLite is a C-language library that implements (...)`, so I dare say SQLite is a library, and so is libSQL :) Both are designed specifically to be used as an integral part of other applications, not separate database systems.

**Comment by glommer** [comment]
Siding with Sarna, we see SQLite (and libSQL) as an embedded library that you can add to your application, not an external database. An example of RDBMS built with it is rqlite.

I am closing this, but mostly because this is a better fit for Discussions, not an issue.
Still, hoping that the explanation is satisfactory
